#вкл/выкл плагин
turn: true
#коорды +-
coords: 500
#сделать чтобы лупа генерила плейс 3 раза (удчано не удачно), после чего брала из кэша
tryLoop: 3
#присылать уведомления о нахождении локs
msgByFound: true
#добавить кд между лупами (мощность) || ms
loopCD: 50



